-- Migration: Seed English for Academic and Professional Purposes (EAPP) curriculum (15 lessons in 4 quarters)
-- Subject: English for Academic and Professional Purposes = subject_id 5 (must exist in your subjects table)
-- PDF base: s3://eel-bucket/subjects/English for Academic and Professional Purposes/
-- Requires: lessons table has quarter_number, quarter_title columns.

SET NAMES utf8mb4;

-- 1) EAPP = subject_id 5. Clear its existing lessons/topics.
DELETE t FROM topics t INNER JOIN lessons l ON t.lesson_id = l.lesson_id WHERE l.subject_id = 5;
DELETE FROM lessons WHERE subject_id = 5;

-- 2) Quarter 1 – Academic Reading and Comprehension
INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 1: Nature and Purpose of Academic Reading', 1, 'Academic Reading and Comprehension');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Definition of academic reading', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 1/Definition of academic reading.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 1: Nature and Purpose of Academic Reading' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Purposes: understanding, evaluating, applying', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 1/Purposes understanding evaluating applying.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 1: Nature and Purpose of Academic Reading' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Difference between academic and casual reading', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 1/Difference between academic and casual reading.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 1: Nature and Purpose of Academic Reading' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 2: Reading Comprehension Strategies', 1, 'Academic Reading and Comprehension');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Skimming and scanning', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 2/Skimming and scanning.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 2: Reading Comprehension Strategies' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Identifying main ideas and supporting details', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 2/Identifying main ideas and supporting details.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 2: Reading Comprehension Strategies' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Making inferences', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 2/Making inferences.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 2: Reading Comprehension Strategies' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Recognizing text structures', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 2/Recognizing text structures.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 2: Reading Comprehension Strategies' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 3: Analyzing Academic Texts', 1, 'Academic Reading and Comprehension');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Distinguishing facts from opinions', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 3/Distinguishing facts from opinions.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 3: Analyzing Academic Texts' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Identifying bias and assumptions', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 3/Identifying bias and assumptions.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 3: Analyzing Academic Texts' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Evaluating credibility of sources', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 3/Evaluating credibility of sources.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 3: Analyzing Academic Texts' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 4: Summarizing and Paraphrasing', 1, 'Academic Reading and Comprehension');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Writing concise summaries', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 4/Writing concise summaries.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 4: Summarizing and Paraphrasing' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Paraphrasing without plagiarism', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 4/Paraphrasing without plagiarism.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 4: Summarizing and Paraphrasing' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Synthesizing information from multiple sources', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 4/Synthesizing information from multiple sources.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 4: Summarizing and Paraphrasing' LIMIT 1;

-- 3) Quarter 2 – Academic Writing Foundations
INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 5: Writing Academic Essays', 2, 'Academic Writing Foundations');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Essay structure: introduction, body, conclusion', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 5/Essay structure introduction body conclusion.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 5: Writing Academic Essays' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Crafting thesis statements', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 5/Crafting thesis statements.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 5: Writing Academic Essays' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Paragraph development', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 5/Paragraph development.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 5: Writing Academic Essays' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 6: Developing Arguments', 2, 'Academic Writing Foundations');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Claim, evidence, reasoning', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 6/Claim evidence reasoning.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 6: Developing Arguments' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Counterarguments', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 6/Counterarguments.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 6: Developing Arguments' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Supporting details and examples', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 6/Supporting details and examples.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 6: Developing Arguments' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 7: Cohesion and Coherence', 2, 'Academic Writing Foundations');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Transitional devices', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 7/Transitional devices.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 7: Cohesion and Coherence' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Paragraph unity', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 7/Paragraph unity.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 7: Cohesion and Coherence' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Logical flow of ideas', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 7/Logical flow of ideas.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 7: Cohesion and Coherence' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 8: Formal Tone and Style', 2, 'Academic Writing Foundations');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Appropriate vocabulary', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 8/Appropriate vocabulary.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 8: Formal Tone and Style' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Avoiding colloquial expressions', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 8/Avoiding colloquial expressions.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 8: Formal Tone and Style' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Academic voice and objectivity', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 8/Academic voice and objectivity.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 8: Formal Tone and Style' LIMIT 1;

-- 4) Quarter 3 – Research Skills and Technical Writing
INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 9: Research Process', 3, 'Research Skills and Technical Writing');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Selecting a research topic', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 9/Selecting a research topic.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 9: Research Process' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Conducting literature review', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 9/Conducting literature review.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 9: Research Process' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Organizing research notes', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 9/Organizing research notes.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 9: Research Process' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 10: Academic Citation and Plagiarism', 3, 'Research Skills and Technical Writing');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'In-text citations (APA, MLA, or Chicago style)', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 10/In-text citations APA MLA Chicago.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 10: Academic Citation and Plagiarism' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Reference list and bibliography', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 10/Reference list and bibliography.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 10: Academic Citation and Plagiarism' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Avoiding plagiarism', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 10/Avoiding plagiarism.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 10: Academic Citation and Plagiarism' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 11: Technical and Professional Writing', 3, 'Research Skills and Technical Writing');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Writing reports, memos, and proposals', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 11/Writing reports memos and proposals.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 11: Technical and Professional Writing' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Email etiquette', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 11/Email etiquette.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 11: Technical and Professional Writing' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Professional formatting', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 11/Professional formatting.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 11: Technical and Professional Writing' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 12: Data Interpretation and Analysis', 3, 'Research Skills and Technical Writing');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Reading charts, graphs, and tables', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 12/Reading charts graphs and tables.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 12: Data Interpretation and Analysis' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Summarizing numerical data in writing', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 12/Summarizing numerical data in writing.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 12: Data Interpretation and Analysis' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Integrating visuals into text', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 12/Integrating visuals into text.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 12: Data Interpretation and Analysis' LIMIT 1;

-- 5) Quarter 4 – Presentation and Portfolio
INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 13: Writing a Position Paper', 4, 'Presentation and Portfolio');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Structuring arguments', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 13/Structuring arguments.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 13: Writing a Position Paper' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Presenting clear evidence', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 13/Presenting clear evidence.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 13: Writing a Position Paper' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Drafting and revising', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 13/Drafting and revising.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 13: Writing a Position Paper' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 14: Oral Presentation Skills', 4, 'Presentation and Portfolio');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Preparing slides or visual aids', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 14/Preparing slides or visual aids.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 14: Oral Presentation Skills' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Effective speech delivery', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 14/Effective speech delivery.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 14: Oral Presentation Skills' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Engaging the audience', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 14/Engaging the audience.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 14: Oral Presentation Skills' LIMIT 1;

INSERT INTO lessons (subject_id, lesson_title, quarter_number, quarter_title) VALUES (5, 'Lesson 15: Portfolio Compilation', 4, 'Presentation and Portfolio');
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Selecting best outputs', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 15/Selecting best outputs.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 15: Portfolio Compilation' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Reflection on learning', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 15/Reflection on learning.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 15: Portfolio Compilation' LIMIT 1;
INSERT INTO topics (lesson_id, topic_title, pdf_path) SELECT lesson_id, 'Final submission of academic portfolio', 's3://eel-bucket/subjects/English for Academic and Professional Purposes/Lesson 15/Final submission of academic portfolio.pdf' FROM lessons WHERE subject_id = 5 AND lesson_title = 'Lesson 15: Portfolio Compilation' LIMIT 1;
